import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';
import {useTestDatabase,type Database} from '../db/index';import {initial,defaultMetrics,valid} from '../lib/data';import * as dashboard from '../app/api/dashboard/route';import * as admin from '../app/api/admin/route';import {sessionHash} from '../lib/admin';import {latestPeriodId,removePeriod} from '../lib/periods';
test('Vercel backend: PostgreSQL, periods, password and persistence',async t=>{
 process.env.DATABASE_URL='postgresql://test-only';process.env.ADMIN_PASSWORD='integration-test-password-2026';
 const pg=new PGlite();await pg.waitReady;
 const query=async(sql:string,values?:any[])=>{const r=await pg.query(sql,values);return {rows:r.rows as any[],rowCount:r.affectedRows??null}};
 const adapter:Database={query,connect:async()=>({query,release(){}})};useTestDatabase(adapter);let cookie='';
 const req=(path:string,method='GET',body?:any,extra:Record<string,string>={})=>new Request('http://localhost:3000'+path,{method,headers:{'Content-Type':'application/json','x-head-write':'1',host:'localhost:3000',origin:'http://localhost:3000',...(cookie?{cookie}:{}),...extra},body:body===undefined?undefined:JSON.stringify(body)});
 let state:any;
 await t.test('creates schema and seeds Jessica without overwriting',async()=>{const r=await dashboard.GET();assert.equal(r.status,200);state=await r.json();assert.equal(state.data.head,'Jessica');assert.equal(state.data.stiPeriods.length,8);assert.deepEqual(state.data,initial);assert.equal((await (await dashboard.GET()).json()).revision,state.revision)});
 await t.test('rejects unauthenticated writes and foreign origins',async()=>{assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:state.data,revision:state.revision}))).status,401);assert.equal((await admin.POST(req('/api/admin','POST',{password:process.env.ADMIN_PASSWORD},{origin:'https://other.example'}))).status,403)});
 await t.test('rejects wrong password and authorizes secure session',async()=>{assert.equal((await admin.POST(req('/api/admin','POST',{password:'wrong'}))).status,401);const r=await admin.POST(req('/api/admin','POST',{password:process.env.ADMIN_PASSWORD}));assert.equal(r.status,200);const setCookie=r.headers.get('set-cookie')!;assert.match(setCookie,/HttpOnly/);assert.match(setCookie,/SameSite=Strict/);cookie=setCookie.split(';')[0];assert.equal((await (await admin.GET(req('/api/admin'))).json()).admin,true)});
 await t.test('validates data and accepts new independent multi-year periods',async()=>{const d=structuredClone(state.data);d.stiPeriods.push({id:'sti-2027-01',label:'Janeiro / 2027',unico:20,mia:2,metrics:{...structuredClone(defaultMetrics),analysts:[{name:'New analyst',tickets:22}]}});d.ismPeriods.push({id:'ism-2027-01',label:'Janeiro / 2027',goal:100});d.clients.forEach((c:any)=>{c.values['ism-2027-01']=null});assert.ok(valid(d));const bad=structuredClone(d);bad.clients[0].values['ism-2027-01']=101;assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:bad,revision:state.revision}))).status,400);assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:d,revision:state.revision,description:'Test save'}))).status,200);const after=await (await dashboard.GET()).json();assert.equal(after.revision,state.revision+1);assert.equal(after.data.stiPeriods.at(-1).label,'Janeiro / 2027');assert.deepEqual(after.data.stiPeriods[7],state.data.stiPeriods[7]);assert.equal(after.data.clients[0].values['ism-2027-01'],null);assert.equal(after.log.length,1);assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:d,revision:state.revision}))).status,409);assert.equal((await (await dashboard.GET()).json()).log.length,1);state=after});
 await t.test('period deletion is admin-only and preserves other months',async()=>{
 assert.equal(latestPeriodId(state.data.stiPeriods),'sti-2027-01');assert.equal(latestPeriodId(state.data.ismPeriods),'ism-2027-01');
 const deleted=removePeriod(removePeriod(state.data,'ism','ism-2027-01'),'sti','sti-2027-01');assert.ok(valid(deleted));assert.equal(deleted.clients[0].values['ism-2027-01'],undefined);assert.deepEqual(deleted.stiPeriods[7],initial.stiPeriods[7]);
 const oldCookie=cookie;cookie='';assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:deleted,revision:state.revision}))).status,401);cookie=oldCookie;
 assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:deleted,revision:state.revision,description:'Periods removed'}))).status,200);state=await (await dashboard.GET()).json();assert.equal(state.data.ismPeriods.length,4);assert.equal(state.data.stiPeriods.length,8);assert.equal(latestPeriodId(state.data.stiPeriods),'sti-7');
 const minimal=structuredClone(state.data);minimal.stiPeriods=[minimal.stiPeriods[0]];assert.throws(()=>removePeriod(minimal,'sti',minimal.stiPeriods[0].id),/pelo menos um/);
 });
 await t.test('password rotation and expired cookies invalidate sessions',async()=>{const old=process.env.ADMIN_PASSWORD!;process.env.ADMIN_PASSWORD='rotated-test-password-2026';assert.equal((await (await admin.GET(req('/api/admin'))).json()).admin,false);process.env.ADMIN_PASSWORD=old;const token=cookie.slice(11);await query('UPDATE hp_admin_sessions SET expires=$1 WHERE id=$2',[Date.now()-1,sessionHash(token)]);assert.equal((await (await admin.GET(req('/api/admin'))).json()).admin,false);const r=await admin.POST(req('/api/admin','POST',{password:old}));cookie=r.headers.get('set-cookie')!.split(';')[0]});
 await t.test('logout revokes write rights',async()=>{assert.equal((await admin.DELETE(req('/api/admin','DELETE'))).status,200);assert.equal((await dashboard.PUT(req('/api/dashboard','PUT',{data:state.data,revision:state.revision}))).status,401)});
 await t.test('rate limit prevents repeated password guesses',async()=>{cookie='';for(let i=0;i<8;i++){assert.equal((await admin.POST(req('/api/admin','POST',{password:'wrong'},{'x-vercel-forwarded-for':'203.0.113.1'}))).status,401)}assert.equal((await admin.POST(req('/api/admin','POST',{password:'wrong'},{'x-vercel-forwarded-for':'203.0.113.1'}))).status,429)});
 await t.test('missing environment shows actionable configuration',async()=>{delete process.env.DATABASE_URL;const r=await dashboard.GET();assert.equal(r.status,503);assert.match((await r.json()).error,/DATABASE_URL/);process.env.DATABASE_URL='postgresql://test-only'});
 await pg.close();
});
