export const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const legacy = {
 year:'', unit:'Não informada', head:'Jessica', stiGoal:800, satisfactionGoal:95, ismGoal:100,
 analysts:[{name:'Andrio',tickets:174},{name:'Ariane',tickets:173},{name:'Kleber',tickets:134},{name:'Aline',tickets:114},{name:'Caroline',tickets:98},{name:'José',tickets:48},{name:'Jéssica',tickets:29},{name:'Eduardo',tickets:16}],
 sti: [721,655,719,770,679,652,860,762].map((unico,i)=>({month:i,unico,mia:[70,18,36,41,26,32,59,27][i]})),
 satisfaction:[95.5,4.5,0,0,0], response:[0.23,1.17,1.31],resolution:[0.44,2.02,2.54], responseGoals:[1,2,4],resolutionGoals:[6,8,16],
 ismMonths:['Abril','Maio','Junho','Julho'], ismPeople:['Jessica','Bob','Rudinei'], clients:[
 {name:'IkatuPlast',values:[94,95,95,96]}, {name:'Fecularia Eldorado',values:[83,85,86,87]}, {name:'Alimentos Agroçales',values:[61,63,63,64]}, {name:'Eletroterras',values:[56,62,68,66]}, {name:'Goias Alimentos',values:[50,56,60,62]}, {name:'JB Mascote',values:[63,63,80,100]}, {name:'Filial BRC',values:[10,50,50,100]}, {name:'Filial Nerial',values:[5,85,100,100]}, {name:'Filial 3 Fronteiras',values:[0,0,70,100]}], notes:''
};

export type Metrics={analysts:{name:string;tickets:number}[];satisfaction:number[];response:number[];resolution:number[];stiGoal:number;satisfactionGoal:number;responseGoals:number[];resolutionGoals:number[]};
export type StiPeriod={id:string;label:string;unico:number;mia:number;metrics:Metrics|null};
export type Data={version:2;head:string;unit:string;notes:string;stiPeriods:StiPeriod[];ismPeriods:{id:string;label:string;goal:number}[];ismPeople:string[];clients:{id:string;name:string;values:Record<string,number|null>}[]};
export const defaultMetrics:Metrics={analysts:legacy.analysts,satisfaction:legacy.satisfaction,response:legacy.response,resolution:legacy.resolution,stiGoal:800,satisfactionGoal:95,responseGoals:legacy.responseGoals,resolutionGoals:legacy.resolutionGoals};
export function upgrade(d:any):Data{if(d.version===2)return d;return {version:2,head:'Jessica',unit:d.unit||'Não informada',notes:d.notes||'',stiPeriods:d.sti.map((s:any)=>({id:'sti-'+s.month,label:months[s.month]+(d.year?' / '+d.year:''),unico:s.unico,mia:s.mia,metrics:s.month===7?{analysts:d.analysts,satisfaction:d.satisfaction,response:d.response,resolution:d.resolution,stiGoal:d.stiGoal,satisfactionGoal:d.satisfactionGoal,responseGoals:d.responseGoals,resolutionGoals:d.resolutionGoals}:null})),ismPeriods:d.ismMonths.map((label:string,i:number)=>({id:'ism-'+i,label:label+(d.year?' / '+d.year:''),goal:d.ismGoal})),ismPeople:d.ismPeople,clients:d.clients.map((c:any,i:number)=>({id:'client-'+i,name:c.name,values:Object.fromEntries(d.ismMonths.map((_:any,j:number)=>['ism-'+j,c.values[j]]))}))};}
export const initial=upgrade(legacy);
export function valid(d:any):d is Data{try{const text=(s:any)=>typeof s==='string'&&s.trim().length>0&&s.length<=200;const n=(v:any,max=10000000)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max;const list=(a:any,max=500)=>Array.isArray(a)&&a.length<=max;const unique=(a:any[])=>new Set(a.map(x=>x.id)).size===a.length;const arr=(a:any,l:number,max=10000000)=>list(a)&&a.length===l&&a.every((v:any)=>n(v,max));return d.version===2&&text(d.head)&&text(d.unit)&&typeof d.notes==='string'&&d.notes.length<=10000&&list(d.stiPeriods)&&d.stiPeriods.length>0&&unique(d.stiPeriods)&&d.stiPeriods.every((s:any)=>text(s.id)&&text(s.label)&&n(s.unico)&&n(s.mia)&&(s.metrics===null||(list(s.metrics.analysts,100)&&s.metrics.analysts.every((a:any)=>text(a.name)&&n(a.tickets))&&arr(s.metrics.satisfaction,5,100)&&Math.abs(s.metrics.satisfaction.reduce((a:number,b:number)=>a+b,0)-100)<.001&&arr(s.metrics.response,3)&&arr(s.metrics.resolution,3)&&arr(s.metrics.responseGoals,3)&&arr(s.metrics.resolutionGoals,3)&&n(s.metrics.stiGoal)&&s.metrics.stiGoal>0&&n(s.metrics.satisfactionGoal,100))))&&list(d.ismPeriods)&&d.ismPeriods.length>0&&unique(d.ismPeriods)&&d.ismPeriods.every((s:any)=>text(s.id)&&text(s.label)&&n(s.goal,100)&&s.goal>0)&&list(d.ismPeople,100)&&d.ismPeople.every(text)&&list(d.clients,100)&&unique(d.clients)&&d.clients.every((c:any)=>text(c.id)&&text(c.name)&&d.ismPeriods.every((s:any)=>c.values[s.id]===null||n(c.values[s.id],100)));}catch{return false}}
